@startuml
'https://plantuml.com/class-diagram

left to right direction
skin rose



package Programa {

    'Clases

    class Videojuego{

        - codigo : int
        - nombre : String
        - precio : int
        - genero : String
        - clasificacionPorEdades : String
        - desarrolladora : String
        - plataforma : String

        + Videojuego(codigo:int, nombre:String, precio:int,genero:String
        clasificacionPorEdades:String, desarrolladora:String, plataforma:String)

        + getCodigo() : int
        + getNombre() :String
        + getPrecio() : int
        + getGenero() : String
        + getClasificacion() : String
        + getDesarrolladora() : String
        + getPlataforma() : String

    }

    class ListaVideojuegos{

        - arregloJuegos : Videojuego[]
        - cantidadMaxima : int
        - cantidadActual : int

        + ListaVideojuegos(cantidadMaxima:int)

        + agregar(juegoNuevo:Videojuego) : boolean
        + obtener(posicion:int) : Videojuego
        + buscar(codigo:int) : int
        + buscar(nombre:String) : int

        + getCantidadMaxima() : int
        + getCantidadActual() : int
        + getArregloJuegos() : Videojuego

    }

    class Empleado{
        - nombreDeUsuario : String
        - contrasena : String
        - comicion : int

        + Empleado(nombreDeUsuario:String, contrasena:String, comicion:int)

        + getNombreUsuario() : String
        + getContrasenia() : String
        + getComicion() : int

    }

    class ListaEmpleados{

        - arregloEmleados : Empleado[]
        - cantidadMaxima : int
        - cantidadActual : int

        + ListaEmpleados(cantidadMaxima:int)

        + agregar(nuevoEmpleado:Empleado) : boolean
        + obtener(posicion:int) : Empleado
        + buscar(codigo:int) : int
        + buscar(nombre:String) : int

        + getCantidadMaxima() : int
        + getCantidadActual() : int
        + getArregloEmpleados() : Empleado

    }

    class Cliente{

        - cuenta : bolean
        - rut : String
        - nombreCompleto : String
        - email : String

        + Cliente(cuenta:boolean, rut:String, nombreCompleto:String, email:String)

        + getCuenta() : boolean
        + getRut() : String
        + getNombreCompleto() : String
        + getEmail() : String

    }

    class ListaClientes{

        - arregloClientes : Cliente[]
        - cantidadMaxima : int
        - cantidadActual : int

        + ListaClientes(cantidadMaxima:int)

        + agregar(nuevoCliente:Cliente) : boolean
        + obtener(posicion:int) : Cliente
        + buscar(codigo:int) : int
        + buscar(nombre:String) : int

        + getCantidadMaxima() : int
        + getCantidadActual() : int
        + getArregloClentes() : Cliente

    }


}


'Relaciones

ListaVideojuegos "1" o-- "10" Videojuego : almacena
ListaEmpleados "1" o-- "5" Empleado : almacena
ListaClientes "1" o-- "*" Cliente : almacena


@enduml
